web/description/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from posts.models import Post

from . import views
from .models import LikeDislike

app_name = "estimation"


urlpatterns = [
    path(
        "posts/like/",
        login_required(views.VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),
        name="post_like",
    ),
    path(
        "posts/dislike/",
        login_required(
            views.VotesView.as_view(model=Post, vote_type=LikeDislike.DISLIKE)
        ),
        name="post_dislike",
    ),
    path(
        "posts/check_estimated/",
        views.CheckEstimatedView.as_view(model=Post),
        name="check_estimated",
    ),
]

web/homepage/urls.py
from django.urls import path
from homepage.views import HomepageView

app_name = "homepage"


urlpatterns = [path("", HomepageView.as_view(), name="home")]

web/posts/urls.py
from django.urls import path

from .views import CreatePostView, PostDetailView

app_name = "posts"


urlpatterns = [
    path("newpost/", CreatePostView.as_view(), name="newpost"),
    path("<int:id>/", PostDetailView.as_view(), name="postdetail"),
]

web/web/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.auth_urls import urlpatterns as auth_urls

from django.views.static import serve
from django.conf.urls import url

from web import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("auth/", include(auth_urls)),
    path("posts/", include("posts.urls", namespace="posts")),
    path("", include("homepage.urls", namespace="homepage")),
    path("category/", include("description.categories_urls", namespace="category")),
    path("comments/", include("django_comments.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("description.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "web.views.page_not_found_view"
handler500 = "web.views.server_error"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

web/homepage/views.py
from core.views import FilterPostByTagMixin
from description.models import Category
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin
from posts.models import Post


class HomepageView(TemplateView, ContextMixin, FilterPostByTagMixin):
    template_name = "homepage/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["posts"] = self.apply_filter(
            Post.objects.get_collection(self.request.user),
            self.request.GET.get("tag_filter", ""),
        )
        context["categories"] = Category.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        context = {}
        context["categories"] = Category.objects.all()
        result = []
        if "input" in request.POST and request.POST["input"]:
            result = Post.objects.filter(
                title__contains=request.POST["input"]
            ).order_by("-creation_date")
        context["posts"] = result
        return render(request, self.template_name, context)

web/templates/homepage/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Post.IT{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock head %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Здесь вы можете найти пост..." aria-describedby="basic-addon2" name='input'>
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">🔎</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="posts col-9">
            <a class="btn btn-primary" id='newpost' href='{% url 'posts:newpost' %}'>Создать публикацию</a>
            {% include 'posts/posts.html' %}
        </div>
        <aside class='col-3'>
            <h4>Категории:</h4>
            <ul class='list-group'>
                {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}">
                        <li class='list-group-item d-flex justify-content-between' style='background: {{ category.color }}'>
                            {{ category.name }}
                        </li>
                    </a>
                {% endfor %}
            </ul>
        </aside>
    </div>
{% endblock content %}
{% block 'scripts' %}
    <script>
        const like_url = '{% url "estimation:post_like" %}';
        const dislike_url = '{% url "estimation:post_dislike" %}';
        const check_estimated_url = '{% url "estimation:check_estimated" %}';
    </script>
    <script src="{% static 'js/estimation.js' %}"></script>
{% endblock 'scripts' %}