web/homepage/urls.py
from django.urls import path
from homepage.views import HomepageView

app_name = "homepage"


urlpatterns = [path("", HomepageView.as_view(), name="home")]

web/users/urls.py
from django.urls import path

from .views import (ProfileView, UserDetailView, UserListView, validate_email,
                    validate_username)

app_name = "users"


urlpatterns = [
    path("", UserListView.as_view(), name="user_list"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("<username>/", UserDetailView.as_view(), name="user_detail"),
    path("validate_username", validate_username, name="validate_username"),
    path("validate_email", validate_email, name="validate_email"),
]

web/web/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.auth_urls import urlpatterns as auth_urls

from django.views.static import serve
from django.conf.urls import url

from web import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("auth/", include(auth_urls)),
    path("posts/", include("posts.urls", namespace="posts")),
    path("", include("homepage.urls", namespace="homepage")),
    path("category/", include("description.categories_urls", namespace="category")),
    path("comments/", include("django_comments.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("description.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "web.views.page_not_found_view"
handler500 = "web.views.server_error"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Web project{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrapmin.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'favicons/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'favicons/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'favicons/favicon-16x16.png' %}"
    />
    {% block head %}{% endblock head %}
</head>
<body class='d-flex flex-column min-vh-100'>
    {% include 'header.html' %}
    <main class='container-fluid'>
        {% block content %}
            Контент забрали инопланетяне :(
        {% endblock content %}
    </main>
    {% include 'footer.html' %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block 'scripts' %}{% endblock 'scripts' %}
</body>
</html>

web/templates/footer.html
<footer id='page_footer' class='mt-auto'>©Copyright</footer>

web/templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'homepage:home' %}">
    <img width="50px" src="{% static 'images/logo.png' %}">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:home' %}">Главная<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'users:user_list' %}">Пользователи</a>
      </li>
    </ul>
    {% if request.user.is_authenticated %}
    <form class="form-inline my-2 my-lg-0">
      {% if request.user.avatar %}
      <img style="clip-path: circle();" width="30px" src="{{ request.user.avatar.url }}">
      {% endif %}
      {{ request.user.username }}
      <a class="nav-link active" href="{% url 'users:profile' %}">Профиль</a>
      <a>/</a>
      <a class="nav-link active" href="{% url 'logout' %}">Выход</a>
    </form>
    {% else %}
    <form class="form-inline my-2 my-lg-0">
      <a class="nav-link active" href="{% url 'login' %}">Логин</a>
      <a>/</a>
      <a class="nav-link active" href="{% url 'sign_up' %}">Регистрация</a>
    </form>
    {% endif %}
  </div>
</nav>