web/users/urls.py
from django.urls import path

from .views import (ProfileView, UserDetailView, UserListView, validate_email,
                    validate_username)

app_name = "users"


urlpatterns = [
    path("", UserListView.as_view(), name="user_list"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("<username>/", UserDetailView.as_view(), name="user_detail"),
    path("validate_username", validate_username, name="validate_username"),
    path("validate_email", validate_email, name="validate_email"),
]

web/web/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.auth_urls import urlpatterns as auth_urls

from django.views.static import serve
from django.conf.urls import url

from web import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("auth/", include(auth_urls)),
    path("posts/", include("posts.urls", namespace="posts")),
    path("", include("homepage.urls", namespace="homepage")),
    path("category/", include("description.categories_urls", namespace="category")),
    path("comments/", include("django_comments.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("description.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "web.views.page_not_found_view"
handler500 = "web.views.server_error"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

web/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.urls import reverse
from django.utils import timezone

from .managers import CustomUserManager
from .validators import validate_for_mobile, validate_for_username


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField("Почта", unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    avatar = models.ImageField("Аватарка", upload_to="uploads/", null=True, blank=True)
    username = models.CharField(
        "Никнэйм", max_length=50, unique=True, validators=[validate_for_username]
    )
    first_name = models.CharField("Имя", max_length=50, null=True, blank=True)
    last_name = models.CharField("Фамилия", max_length=50, null=True, blank=True)
    birthday = models.DateField("Дата рождения", null=True, blank=True)
    mobile = models.PositiveIntegerField(
        "Номер телефона", null=True, blank=True, validators=[validate_for_mobile]
    )
    description = models.TextField("Описание", null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects = CustomUserManager()

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:user_detail", kwargs={"username": self.username})

    def get_full_name(self):
        return f"{str(self.first_name).capitalize()} {str(self.last_name).capitalize()}"


class Subscription(models.Model):
    person = models.ForeignKey(
        "CustomUser",
        verbose_name="Пользователь",
        on_delete=models.CASCADE,
        related_name="person_who_has_subscribers",
    )
    subscriber = models.ForeignKey(
        "CustomUser",
        verbose_name="Подписчик",
        on_delete=models.CASCADE,
        related_name="subscribers",
    )
    is_subscribed = models.BooleanField(
        "Подписка активна",
        default=True,
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"

    def __str__(self):
        return f"{self.subscriber} подписался на {self.person}"

web/users/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label="Пароль")
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(), label="Подвердите пароль"
    )
    captcha = CaptchaField(label="Пройдите проверку, что вы не робот.")

    class Meta:
        model = CustomUser
        fields = (
            CustomUser.username.field.name,
            CustomUser.email.field.name,
            CustomUser.password.field.name,
        )
        labels = {
            CustomUser.username.field.name: "Никнэйм",
            CustomUser.email.field.name: "E-mail",
            CustomUser.password.field.name: "Пароль",
        }

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        email = cleaned_data.get("email")
        username = cleaned_data.get("username")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error("confirm_password", "Пароли не совпадают")
        if CustomUser.objects.filter(email=email):
            self.add_error(
                CustomUser.email.field.name,
                "Пользователь с таким email уже существует, попробуйте войти в аккаунт.",
            )
        if CustomUser.objects.filter(username=username):
            self.add_error(
                CustomUser.username.field.name,
                "Пользователь с таким ником уже существует, придумайте новый никнэйм.",
            )
        return cleaned_data

    def register(self):
        cleaned_data = super(RegistrationForm, self).clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        email = cleaned_data.get("email")
        CustomUser.objects.create_user(
            username=username, email=email, password=password
        )


class Profile(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "avatar",
            "birthday",
            "mobile",
            "description",
        )
        widgets = {
            "birthday": forms.DateInput(attrs={"type": "date"}),
        }

web/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import FormView, TemplateView
from django.views.generic.base import ContextMixin
from posts.models import Post

from .forms import Profile, RegistrationForm
from .models import CustomUser, Subscription

User = get_user_model()


class UserListView(TemplateView):
    template_name = "users/user_list.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.get_context_data())

    def post(self, request, *args, **kwargs):
        result = CustomUser.objects.get_all_active_users()
        if inputted := request.POST.get("input"):
            result = result.filter(username__startswith=inputted)
        return render(
            request, self.template_name, context=self.get_context_data(result)
        )

    def get_context_data(self, users_to_find=CustomUser.objects.get_all_active_users(), **kwargs):
        context = super().get_context_data(**kwargs)
        users = []
        for user in users_to_find:
            followers = Subscription.objects.filter(person=user, is_subscribed=True).count()
            following = Subscription.objects.filter(subscriber=user, is_subscribed=True).count()
            posts = len(Post.objects.filter(author=user))
            user_to_add = {
                "avatar": user.avatar,
                "username": user.username,
                "description": user.description,
                "followers": followers,
                "following": following,
                "posts": posts,
            }
            users.append(user_to_add)
        context["users"] = users
        return context


class UserDetailView(TemplateView):
    template_name = "users/user_detail.html"

    def get(self, request, username, *args, **kwargs):
        user = get_object_or_404(CustomUser, username=username, is_active=True)
        posts = Post.objects.filter(author=user)
        followers = Subscription.objects.filter(person=user, is_subscribed=True).count()
        following = Subscription.objects.filter(subscriber=user, is_subscribed=True).count()
        if request.user.is_authenticated:
            if_person_follows = Subscription.objects.filter(
                person=user, subscriber=request.user, is_subscribed=True
            )
        else:
            if_person_follows = False
        context = {
            "user": user,
            "posts": posts,
            "followers": followers,
            "following": following,
            "if_person_follows": if_person_follows,
        }
        return render(request, self.template_name, context)

    def post(self, request, username, *args, **kwargs):
        user = get_object_or_404(CustomUser, username=username, is_active=True)
        if "follow" in request.POST and request.POST["follow"] == "Подписаться":
            sub = Subscription(person=user, subscriber=request.user)
            sub.save()
        else:
            sub = Subscription.objects.get(person=user, subscriber=request.user)
            if sub:
                sub.delete()
        return redirect("users:user_detail", username)


class SignupView(FormView):
    form_class = RegistrationForm
    success_url = "/auth/login/"
    template_name = "users/auth/signup.html"

    def form_valid(self, form):
        form.register()
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class ProfileView(TemplateView, ContextMixin):
    template_name = "users/profile.html"

    def post(self, request, *args, **kwargs):
        user = request.user
        user_form = Profile(request.POST or None, request.FILES or None, instance=user)
        if user_form.is_valid():
            user_form.save()
            return redirect("/users/profile")
        else:
            return self.get(request, {"form": user_form})

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.get_context_data())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["form"] = Profile(self.request.POST or None, instance=self.request.user)
        context["posts"] = Post.objects.filter(author=self.request.user)
        return context


def validate_username(request):
    username = request.GET.get("username", None)
    response = {
        "is_username_taken": User.objects.filter(username__iexact=username).exists(),
    }
    return JsonResponse(response)


def validate_email(request):
    email = request.GET.get("email", None)
    response = {
        "is_email_taken": User.objects.filter(email__iexact=email).exists(),
    }
    return JsonResponse(response)

web/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профиль{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock head %}
{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                {% if user.avatar %}
                    <img class="rounded-circle mt-5" width="150px" src="{{ user.avatar.url }}">
                {% else %}
                    <img class="rounded-circle mt-5" width="150px" src="{% static 'images/user.jpg' %}">
                {% endif %}
                <span class="font-weight-bold">@{{ user.username }}</span><span class="text-black-50">{{ user.email }}</span>
                <span></span>
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Настройки профиля</h4>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    <div class="row mt-3">
                        {% if form.errors %}
                            <p>
                            {% if form.errors.items|length == 1 %}
                                Пожалуйста, исправьте ошибку ниже.
                            {% else %}
                                Пожалуйста, исправьте ошибки ниже.
                            {% endif %}
                            </p>
                        {% endif %}
                        {% for field in form %}
                            {{ field.errors }}
                            <div class="col-md-12 p-2">
                                {% if field.name == "description" %}
                                    <label class="labels">{{ field.label }}</label>
                                    <textarea name="description" cols="40" rows="5" id="id_description" class="form-control">{{ field.value }}</textarea>
                                {% elif field.name == 'avatar' %}
                                    <label class="labels">Изменить фотографию:</label><br>
                                    <input type="file" name="avatar" accept="image/*" id="id_avatar">
                                {% elif field.name == "birthday" %}
                                    <label class="labels">{{ field.label }}</label>
                                    <input type="date" name="birthday" class="form-control" value="{{ field.value|date:'Y-m-d' }}" id="id_birthday">
                                {% else %}
                                    <label class="labels">{{ field.label }}</label>
                                    <input type="{{ field.type }}" class="form-control" name="{{ field.name }}" 
                                    {% if field.value != None %}
                                        value="{{ field.value }}"
                                    {% endif %}
                                    maxlength="{{ field.maxlength }}" id="{{ field.id }}">
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mt-4 text-center">
                        <input type="submit" class="btn btn-primary" value="Сохранить">
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <a href="{% url 'logout' %}" class="btn btn-danger">Выйти из аккаунта</a>
            <a href="{% url 'password_change' %}" class="btn btn-info">Изменить пароль</a>
            <a href="{% url 'users:user_detail' user.username %}" class="btn btn-primary">Ваша страница</a>
            {% for post in posts %}
                {% include 'include/post.html' %}
            {% endfor %}
        </div>
    </div>
</div>
</div>
</div>
{% endblock content %}

web/templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/user_detail.css' %}">
{% endblock head %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col-md-12">
         <div id="content" class="content content-full-width">
            <!-- begin profile -->
            <div class="profile">
               <div class="profile-header">
                  <!-- BEGIN profile-header-cover -->
                  <div class="profile-header-cover"></div>
                  <!-- END profile-header-cover -->
                  <!-- BEGIN profile-header-content -->
                  <div class="profile-header-content">
                     <!-- BEGIN profile-header-img -->
                     <div class="profile-header-img">
                        {% if user.avatar %}
                           <img src="{{ user.avatar.url }}" alt="">
                        {% else %}
                           <img src="{% static 'images/user.jpg' %}" alt="">
                        {% endif %}
                     </div>
                     <!-- END profile-header-img -->
                     <!-- BEGIN profile-header-info -->
                     <div class="profile-header-info">
                        <h4 class="m-t-10 m-b-5">{{ user.username}}</h4>
                        <p class="m-b-10" style="word-wrap: break-word;">{{ user.description }}</p>
                        <form action="{% url 'users:user_detail' user.username %}"method="post">
                           {% csrf_token %}
                           {% if request.user.is_authenticated %}
                              {% if request.user == user %}
                                 <a class="btn btn btn-info mb-2" href={% url 'users:profile' %}>Изменить профиль</a>
                              {% elif if_person_follows %}
                                 <input class="btn btn btn-info mb-2" type='submit' name='follow' value='Отписаться'>
                              {% else %}
                                 <input class="btn btn btn-info mb-2" type='submit' name='follow' value='Подписаться'>
                              {% endif %}
                           {% endif %}
                        </form>
                        <span class="number"><span class="follow">Подписчики:</span> {{ followers }}</span>
                        <span class="number"><span class="follow">Подписки:</span> {{ following }}</span>
                     </div>
                  </div>
                  <!-- END profile-header-content -->
               </div>
            </div>
            <!-- end profile -->
            {% for post in posts %}
                {% include 'include/post.html' %}
            {% endfor %}
         </div>
      </div>
   </div>
</div>
{% endblock content %}

web/templates/users/user_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/user_list.css' %}">
{% endblock head %}
{% block content %}
    <form method='post'>
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Здесь вы можете найти пользователя по нику..." aria-describedby="basic-addon2" name='input'>
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">🔎</button>
            </div>
        </div>
    </form>
    <div class="row d-flex mt-4 mb-4">
        {% for user in users %}
        <div class="col-12 col-sm-6 col-lg-3">    
            <div class="container mt-5 d-flex justify-content-center">
                <div class="card p-3">
                    <div class="d-flex align-items-center">
                        <div class="image">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" class="rounded" width="80" >
                    {% else %}
                        <img src="{% static 'images/user.jpg' %}" class="rounded" width="80" >
                    {% endif %}
                    </div>
                    <div class="ml-3 w-100">
                       <h4 class="mb-0 mt-0">{{ user.username }}</h4>
                       <span>{{ user.description|default:''|truncatechars:24 }}</span>
                       <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                        <div class="d-flex flex-column">
                            <span class="articles">Посты</span>
                            <span class="number1">{{ user.posts }}</span>
                        </div>
                        <div class="d-flex flex-column">
                            <span class="followers">Подписчики</span>
                            <span class="number2">{{ user.followers }}</span> 
                        </div>
                        <div class="d-flex flex-column">
                            <span class="rating">Подписки</span>
                            <span class="number3">{{ user.following }}</span>  
                        </div>   
                    </div>
                       <div class="button mt-2 d-flex flex-row align-items-center">
                        <a class="btn btn-sm btn-primary w-100 ml-2" href="{% url 'users:user_detail' user.username %}">Профиль</a>               
                       </div>
                    </div>                 
                    </div>
              </div>   
             </div>
            </div>
        {% empty %}
            <h3>Ничего не найдено...</h3>
        {% endfor %}
        </div>
{% endblock content %}