web/description/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from posts.models import Post

from . import views
from .models import LikeDislike

app_name = "estimation"


urlpatterns = [
    path(
        "posts/like/",
        login_required(views.VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),
        name="post_like",
    ),
    path(
        "posts/dislike/",
        login_required(
            views.VotesView.as_view(model=Post, vote_type=LikeDislike.DISLIKE)
        ),
        name="post_dislike",
    ),
    path(
        "posts/check_estimated/",
        views.CheckEstimatedView.as_view(model=Post),
        name="check_estimated",
    ),
]

web/posts/urls.py
from django.urls import path

from .views import CreatePostView, PostDetailView

app_name = "posts"


urlpatterns = [
    path("newpost/", CreatePostView.as_view(), name="newpost"),
    path("<int:id>/", PostDetailView.as_view(), name="postdetail"),
]

web/users/urls.py
from django.urls import path

from .views import (ProfileView, UserDetailView, UserListView, validate_email,
                    validate_username)

app_name = "users"


urlpatterns = [
    path("", UserListView.as_view(), name="user_list"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("<username>/", UserDetailView.as_view(), name="user_detail"),
    path("validate_username", validate_username, name="validate_username"),
    path("validate_email", validate_email, name="validate_email"),
]

web/web/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.auth_urls import urlpatterns as auth_urls

from django.views.static import serve
from django.conf.urls import url

from web import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("auth/", include(auth_urls)),
    path("posts/", include("posts.urls", namespace="posts")),
    path("", include("homepage.urls", namespace="homepage")),
    path("category/", include("description.categories_urls", namespace="category")),
    path("comments/", include("django_comments.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("description.urls")),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "web.views.page_not_found_view"
handler500 = "web.views.server_error"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

web/posts/models.py
from ckeditor.fields import RichTextField
from description.models import Category, LikeDislike, TaggedWhatever
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django.core.files.images import get_image_dimensions
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from posts.managers import PostManager
from sorl.thumbnail import get_thumbnail
from taggit.managers import TaggableManager

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=64, default="title", verbose_name="Заголовок")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, verbose_name="Автор"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        null=True,
        blank=True,
        related_name="posts",
    )
    text = RichTextField(verbose_name="Текст", null=False)
    creation_date = models.DateTimeField("Дата создания", auto_now=True, editable=False)
    votes = GenericRelation(LikeDislike, related_query_name="posts")
    tags = TaggableManager(through=TaggedWhatever)

    objects = PostManager()

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"

    def __str__(self):
        return self.title[:30]

    def get_absolute_url(self):
        return reverse("posts:postdetail", kwargs={"id": self.pk})


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(
        verbose_name="Изображение",
        upload_to="uploads/",
    )

    class Meta:
        verbose_name = "Фотография, связанная с постом"
        verbose_name_plural = "Фотографии, связанные с постом"

    def __str__(self):
        return self.post.title

    def get_image(self, img_width, img_height):
        width, height = get_image_dimensions(self.image.file)
        resize = min(width / img_width, height / img_height)
        return get_thumbnail(
            self.image,
            f"{int(resize * width)}x{int(resize * height)}",
            crop="center",
            quality=100,
        )

    def get_image_1200x1200(self):
        return self.get_image(1200, 1200)

    def image_tmb(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="50">')
        return "Изображение отсутствует"

    image_tmb.short_description = "Превью"
    image_tmb.allow_tags = True

web/posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "category",
            "text",
            "tags",
        ]

    attachments = forms.ImageField(
        required=False,
        label="Изображения",
        widget=forms.ClearableFileInput(attrs={"multiple": True})
    )

web/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, DetailView
from posts.forms import PostForm
from posts.models import Post

from .models import PostImage


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/new_post.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save()
        for item in self.request.FILES.getlist("attachments"):
            PostImage.objects.create(image=item, post=post)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("homepage:home")


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    pk_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        post = self.get_object()
        context = super().get_context_data(**kwargs)
        context["images"] = PostImage.objects.filter(post_id=post.id)
        return context

web/templates/include/comment.html
<div class="comment">
    <div class="card">
        <div class="card-header">
            <h5>
                <a href="{% url 'users:user_detail' comment.user %}">
                    {{ comment.user.username }}
                </a>
            </h5>
        </div>
        <div class="card-body">
            {% autoescape off %}
                <p class="card-text">{{ comment.comment }}</p>
            {% endautoescape %}
        </div>
        <div class="card-footer">
            <div class='row justify-content-end'>
                <div class="text-muted">{{ comment.submit_date }}</div>
            </div>
        </div>
    </div>
</div>

web/templates/include/comment_form.html
{% load custom_tags %}
<div class="card">
    <header class="card-header">
        <h5>Добавить комментарий</h5>
    </header>
    <form action="{{ comment_form_target_value }}" method="POST">
        {% csrf_token %}
        {{ form.honeypot }}
        {{ form.content_type }}
        {{ form.object_pk }}
        {{ form.timestamp }}
        {{ form.security_hash }}
        <div class="card-body">
            {{ form.comment|add_classes:'comment-text' }}
        </div>
        <footer class="card-footer">
            <input class='btn btn-success' type="submit" value="Оставить комментарий" id="id_submit" />
        </footer>
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
</div>

web/templates/include/estimation.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/estimation.css' %}">
</head>
<div class="estimation d-flex flex-row pt-3">
    <div class="likes d-flex flex-row justify-content-between align-items-center">
        <svg data-action='like' data-pk='{{ post.pk }}' data-type='Post' class='estimation-icon estimation-icon-disabled' viewBox="0 0 24 24"><g><path d="M18.77,11h-4.23l1.52-4.94C16.38,5.03,15.54,4,14.38,4c-0.58,0-1.14,0.24-1.52,0.65L7,11H3v10h4h1h9.43 c1.06,0,1.98-0.67,2.19-1.61l1.34-6C21.23,12.15,20.18,11,18.77,11z M7,20H4v-8h3V20z M19.98,13.17l-1.34,6 C18.54,19.65,18.03,20,17.43,20H8v-8.61l5.6-6.06C13.79,5.12,14.08,5,14.38,5c0.26,0,0.5,0.11,0.63,0.3 c0.07,0.1,0.15,0.26,0.09,0.47l-1.52,4.94L13.18,12h1.35h4.23c0.41,0,0.8,0.17,1.03,0.46C19.92,12.61,20.05,12.86,19.98,13.17z"></path></g></svg>
        <span data-count='like' class="text-muted">{{ post.votes.likes.count }}</span>
    </div>
    <div class="dislikes d-flex flex-row justify-content-between align-items-center">
        <svg data-action='dislike' data-pk='{{ post.pk }}' data-type='Post' class='estimation-icon estimation-icon-disabled' viewBox="0 0 24 24"><g><path d="M17,4h-1H6.57C5.5,4,4.59,4.67,4.38,5.61l-1.34,6C2.77,12.85,3.82,14,5.23,14h4.23l-1.52,4.94C7.62,19.97,8.46,21,9.62,21 c0.58,0,1.14-0.24,1.52-0.65L17,14h4V4H17z M10.4,19.67C10.21,19.88,9.92,20,9.62,20c-0.26,0-0.5-0.11-0.63-0.3 c-0.07-0.1-0.15-0.26-0.09-0.47l1.52-4.94l0.4-1.29H9.46H5.23c-0.41,0-0.8-0.17-1.03-0.46c-0.12-0.15-0.25-0.4-0.18-0.72l1.34-6 C5.46,5.35,5.97,5,6.57,5H16v8.61L10.4,19.67z M20,13h-3V5h3V13z"></path></g></svg>
        <span data-count='dislike' class="text-muted">{{ post.votes.dislikes.count }}</span>
    </div>
</div>
{% comment "scripts" %}

    If you import it, you need to include these scripts blocks:

    <script>
        const like_url = '{% url "estimation:post_like" %}'
        const dislike_url = '{% url "estimation:post_dislike" %}'
        const check_estimated = '{% url "estimation:check_estimated" %}'
    </script>
    <script src="{% static 'js/estimation.js' %}"></script>

{% endcomment %}

web/templates/include/post.html
<div class="post">
    <div class="card">
        <div class="card-header" style="background-color: {{ post.category.color }}">
            <h4>{{ post.title }}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ post.category|default:"" }}</h5>
            {% autoescape off %}
                <p class="card-text">{{ post.text|truncatechars:140 }}</p>
            {% endautoescape %}
            <h6 class="card-subtitle mb-2 text-muted">
                {% for tag in post.tags.all %}
                    <a href="{{ tag.get_absolute_filter_url }}">#{{ tag }}</a>
                {% endfor %}
                {{post.tag}}
            </h6>
            {% include 'include/estimation.html' %}
            <footer class="blockquote-footer">
                <a href="{% url 'users:user_detail' post.author %}">
                    @{{ post.author }}
                </a>
            </footer>
        </div>
        <div class="card-footer">
            <div class='row justify-content-between align-items-center'>
                <div class="col">
                    <div class="text-muted">{{ post.creation_date }}</div>
                </div>
                <div class="col d-flex justify-content-end">
                    <a class='btn btn-primary' href="{% url 'posts:postdetail' post.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
</div>

web/templates/include/standard_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/auth_forms.css' %}">
{% endblock head %}

{% block content %}
    {% block content_before_form %}{% endblock content_before_form %}
        <div class="card">
            <div class="card-header text-white bg-secondary">
                {% block header %}{% endblock header %}
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">{% block submit %}{% endblock submit %}</button>
                </form>
            </div>
        </div>
    {% block content_after_form %}{% endblock content_after_form %}
{% endblock %}